[package]
name = "soft_skia"
version = "0.4.0"
edition = "2021"
description="software rasterization skia binding"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.5"
tiny-skia = "0.9.0"
base64 = "0.21.0"