name: Rust

on:
  push:
    branches:
      - main
      - '0\.*\.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: soft-skia
        run: |
          cd soft-skia
          cargo build
          cargo test

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: soft-skia-wasm
        run: |
          cd soft-skia-wasm
          cargo install wasm-pack
          wasm-pack build --release --target web

      - name: vue-skia-framework
        run: |
          cd vue-skia-framework
          pnpm i
          pnpm build

      - name: vue-playground
        run: |
          cd vue-playground
          pnpm i
          pnpm build
      - name: Archive vue-skia-framework artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vue-skia-framework
          path: |
            vue-skia-framework
            !node_modules
      - name: Archive vue-playground results
        uses: actions/upload-artifact@v3
        with:
          name: vue-playground
          path: vue-playground/dist