name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.x
    # File containing the ve
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: soft-skia
        run: |
          cd soft-skia
          cargo build
          cargo test

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: soft-skia-wasm
        run: |
          cargo install wasm-pack
          cd soft-skia-wasm
          wasm-pack build --release --target web

      - name: vue-skia-framework
        run: |
          cd vue-skia-framework
          pnpm i
          pnpm run build

      - name: vue-playground
        run: |
          cd vue-playground
          pnpm i
          pnpm run build

      - name: Archive vue-skia-framework artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vue-skia-framework
          path: |
            vue-skia-framework/lib
            vue-skia-framework/type.d.ts
            vue-skia-framework/main.js
            vue-skia-framework/main.d.ts
            vue-skia-framework/components
            vue-skia-framework/LICENSE
            vue-skia-framework/package-publish.json

      - name: Archive soft-skia-wasm artifacts
        uses: actions/upload-artifact@v3
        with:
          name: soft-skia-wasm
          path: |
            soft-skia-wasm/pkg
