name: Rust

on:
  push:
    branches:
      - main
      - '0\.*\.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: soft-skia
        run: |
          cd soft-skia
          cargo build
          cargo test

      - name: soft-skia-wasm
        run: |
          cd soft-skia-wasm
          cargo install wasm-pack
          wasm-pack build --release --target web

      - name: vue-skia-framework
        run: |
          cd vue-skia-framework
          npm i
          npm run build

      - name: vue-playground
        run: |
          cd vue-playground
          npm i
          npm run build
