name: Playground Use Latest

on:
  push:
    branches:
      - main
      - '0\.*\.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.x
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: vue-playground
        run: |
          cd vue-playground
          cp package-ci.json package.json
          npm i
          npm run build

      - name: Archive vue-playground results
        uses: actions/upload-artifact@v3
        with:
          name: vue-playground-use-latest
          path: |
            vue-playground
            !vue-playground/node_modules